### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by 19940425** [NiryoRobotics/niryo_one_ros_simulation#3]
I am a rookie about NiryoOne and i am want to control it with scripting.
I find two package, "niryo_one_ros_simulation" and "niryo_one_ros" , which one should i use?
Could you help me ?
thank you

**Comment by Wasta-Geek** [comment]
For your case, you should use niryo_one_ros project, if you need to launch NiryoOne in simulation mode (on your desktop) if you want to just work on the script part: roslaunch niryo_one_bringup desktop_rviz_simulation
You can find available launch files here: https://github.com/NiryoRobotics/niryo_one_ros/tree/master/niryo_one_bringup

And for scripting, you may use the python TCP Client to interacts across network https://github.com/NiryoRobotics/niryo_one_ros/tree/master/niryo_one_tcp_server/clients/python or if you want to run a python script running on the robot itself: https://github.com/NiryoRobotics/niryo_one_ros/tree/master/niryo_one_python_api

[Note: This repository was just a copy of the simulation part of the niryo_one_ros but is out of date compared to the niryo_one_ros project so it will be removed. Please rather use niryo_one_ros project.]
